# TODO not sure why these packages are directly needed by yaptest:
#apt-get install g++
#apt-get install libcrypt-ssleay-perl
#apt-get install libmime-base64-perl
#apt-get install libnet-dns-perl
#apt-get install libnet-ldap-perl
#apt-get install libpcap-dev
#apt-get install libssl-dev
#apt-get install libtemplate-perl
apt-get install arp-scan
apt-get install coreutils
apt-get install dnsutils
apt-get install fpdns
apt-get install finger
apt-get install hydra
apt-get install ike-scan
apt-get install iputils-ping
apt-get install john
apt-get install ldap-utils
apt-get install libdbd-pg-perl
apt-get install libdbi-perl
apt-get install libdigest-md4-perl
apt-get install libexpect-perl
apt-get install libfile-temp-perl
apt-get install libhttp-cookies-perl
apt-get install libio-pty-perl
apt-get install libparallel-forkmanager-perl
apt-get install libproc-simple-perl
apt-get install liburi-perl
apt-get install libwww-perl
apt-get install libxml-simple-perl
apt-get install make
apt-get install medusa
apt-get install nbtscan
apt-get install nfs-common
apt-get install nmap
apt-get install ntp
apt-get install onesixtyone
apt-get install openssh-client
apt-get install perl
apt-get install perl-base
apt-get install phantomjs
apt-get install postgresql-9.4
apt-get install rpcbind
apt-get install rstat-client
apt-get install rusers
apt-get install snmp
apt-get install ssh
apt-get install sslscan
apt-get install telnet
apt-get install tftp
apt-get install traceroute
apt-get install x11-apps
apt-get install x11-utils
